apiVersion: v1
kind: Secret
metadata:
  name: confluent-credentials
  namespace: monitoring
type: Opaque
stringData:
  username: GA5I3JOHUN3VXFIK
  password: cfltw07ksH77FcegOPAB7ltz0lDXiU1A0M3hEoy8q16BYWxh27L5ZlorOhORgEUw
