apiVersion: v1
kind: Secret
metadata:
  name: confluent-credentials
  namespace: monitoring
type: Opaque
stringData:
  username: <your metric api key here>
  password: <your confluent metric api secret here>
