apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: confluent-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgB1tO5xLuq9zEvCITfZSaI9X/YzyC5cEl08VUfNpTwXADPvg3C68di4sUJUN/oIeEg5cybwD4xg5oyPaHUsv5yB14EtWb3Z+FiRf9PugGVhrn11QY/L1nejdLDmNe5OUl4lkUTpZOk+G0K3nnqU9d9S4yoOBwy08DY0VhRBtFjw1OpmHHMXas1i3cfdnUzLeaEkFioTI88RLry/6o4hnbXUE1FSZBDJ4veYQGal7o7cqxxM5ynht+i/wC4iu8oN6rVNNRtwFXeb0VwE/02zdexoKoHr6aVn+aDPitW3WO7phzDELnqaiQLfUePzBcs5BGpikfXwbvUcjNmOyCMkipyRVSRO946ff6Q6EmOCjxV7ja33wqSnqKaj0Ho9XSlUS7E3rGMWCfoYEf6bmKsUaMyMYRzEpm4/nIpkmWS/U/tnuRZp8c0K6HYFgmN+OMVD45DL9JjLyQWcK4A7JpFocS2c8AmbTpKVG97+xFypyrbzoageJf6xb0wrS2NqxnBkMdNBhaDKBFN7sKKS5UMr55WIAQas9lqUU9o+A7NRG3HYv15s4wRVLpjRXKh0O7b9/40Mz/zgxV8bkMmfxJcvCTcaqdSQQ0wOJ3GuHI/eiRvLp8cQKx/bUGJwH/TMizD1MH67UWtQ2fMl0H/ql2n0ulYmf7vTn9k1H/HKRhKKyi6GMjXF1EVR1UH7WtJ7Ac1hivoemLmlseBDAFE5yAyPA5pHO7uJ2DnOocrKafFps+aO2R19CuGW80NHEdhXalAdQWrTnQqcgM7ti4oMJrosHte6
    username: AgCJ0dGaTr+qNoJy1kMWYHlecnnXXzbwo0bYD4/L54ensmcuwnyFq0OjagVf7kQ0OKgkqKGqXL5RqbartL5FyLQo1OFD1C7RWANwOiElYNSLq19XbV/hERLyvi/nbnW+Kyd+Thp5SXBd5QGM8r17C0+zz1n5s6Y4lGsNk2KrK5DvtKrIhQVCNmFAXuOd15usCxk1pYwawY1HuWhlHMB4/Q76UvEl8r5oZTwJWaPkdrnVM+MD+VWchqPFjtHX7npBKK1ZeUvrDqPFiQ30Q8NYscPXzEaISkPGNIMF0hK/LiZSFX0UbH4fX/x1EGaqrWmzZUJRysSYSoXXrn1yyVzYWqcqCCcx6aUr6myfEpgveR1A6c8tkkdQBqGb9RUv2502vuPf2f2eknnByeUWqSnK5JORJJ022NMS9C10N9kMEKJ+yvc7o+hcmW8fOEAjOu8byr0pw1vc50VyUXJ2+dGEUSf/JVaxuP1Cvg6yj7LQdgwRc246vQzLrCCJ/2a+43TzXuGZEU1ewBj9RVm6TyyTPAt5F/UQ7zGit8WaeFr9+B/UQn3OqQaPdkF1HkFwRhEk+0Aw3U4g8Ofx2k/+lJQUdbc3fILeVuTOPZGSlHb7pDBz/867PHaglt50fP0wt5qUCco5aXXmE2rwpy/EB28vvoTp5p6YwU/aT+/8psE8jIoCUByjRdw3tMafH4iDTb4CQKw/+UgV+/gr+h5gzpIViRut
  template:
    metadata:
      creationTimestamp: null
      name: confluent-credentials
      namespace: monitoring
    type: Opaque

