apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: confluent-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgAWheKRwDtnugQ7mToNT1NnsNpGavho+/6m2NS2yYt1B9pGaeRfeQI1a5WitHZ2zC3L4qtiGufQP3PmAEkDquGXCfnIPREIDAXgIVAi7aTYx8mWVGYP1gA0R4rOocP4MVH+T8v6hWc/7HC3wIpEviHPm7UC3O+Y9EitfbPP9TYbhUCKhsVQufGA8rVFaCLRklHGusN5hh/EQlaVfHKeAlFc5RgXVXgzW9TUZuXDzNc0Xajwu1Jhbtz99nfhuNo+aefs+7NtUYtLjKdk9sSJ2FfVP+IJPoY3VQS6iTZpq7mZrLDGeno+5FKE/gaeZJWhyocIkD3mecn7pwQIyTRyNEA8XoBRdHlwI0UZlaa/EgaWmG1y1uCD+J//iPem4OT8SZwVAphkeSg7Q8KQvNjO5tkYOtip1mfPLwfkug37WcYa1cftuvmRH1O8nLDXDZLp4QejyjAjvH8eCD6TXepuuTXoArkG/mP7nYLl/iy2CB8GKqrlqNJQKVW/GGkMGXulojfAlM5Rt9qxoEFjCvkuK/sTNDZoklzoGntkYc3eK6bUNkw1T4aHBD7B7sOZrYgua+OWvp3F731oGKZuNxp9GSw15TSULsMTfUDYo06bSv+YFLYz3kGmkk1BwxROOzugEXZn/7Uu5GUK7gkCSmSDMYFiWjv/pPyr1KYgZ7VeV9NAZucYTXKyX6nhpitSCVDrRtSKN2sIHC9GFdTSRbeKtI4IUVHZl1WK7uutvA8JBlPt7Z2u+g/eh4bFAVWgh3sMh5X5YRwtFj/fyTIF/di77f6w
    username: AgBY2o0Cia9O9qeFDZs/f6ImCb4cFHegF8+y1xecDHOLTp5FAoFdm8wTgJ8ausl1hyx9TOLYnNLY2tFIvgBiwOSf46nizD7FjPStvuTaK776CKk49QMogf6Em7a2cnVjWCzcYGov5egQbgr2FdJO94HbSKDivmW1uZ/9AUyff4GoqLqwsWgmBpv7qm7QhSS0q/sGMB2CU2mfBode92Gzv4eZV4V++5131C4EgG9GfgYcZhQGzx11nMGRFGUNmildEG6M9nkP2lRvdXlDBXFisrJbt5Swgl2oSGXcMAGau+e9guyevaMq2ar6T6TzZGItybKE1NLunVjWzrhLKDtcOoVnGdQVhsGuqcAsbx+is1RKHt2JPRE0Nst7yRTiaxPjbyo2NruP3p0SMN7wsVssbTB2YyIVoLrLMON+114DjgkhZZCVBl/YjBTZRDJ2i5XlKUp7KsD1U+Z46fKaONSlX/H6AXY94OvqSpNjjQfFvqCc7biKlQ2agRBb+nLjeoT+3vPIchFU4kZvmv8FugVUnwky/sHWVLeUsGw8an04OpKxiO7Sp6kZ1SEOGYGLbxtN94uRGFCP/v27t8yexH+VVEGYReQ1WDr0srbZIVbPbrSO5lATNcjgBtP2o+PcfRdkc9L8M21zzD9w0IXBZiTp2oNq1eZFi+Zywwc/K/fYo9DyaIJY3dC5JmxcEUT6Po/34NRQGtssGxX2vDS/P/s8QICh
  template:
    metadata:
      creationTimestamp: null
      name: confluent-credentials
      namespace: monitoring
    type: Opaque

