apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-app-webhook
  namespace: monitoring
spec:
  encryptedData:
    slack_api_url: AgCaalr5HzFG3CRw1Eueko29NHrM0BvqZFiBHeoSxmlBUMXAH7KVuDl7h+H4IAB73KU8qJZl77k1hJaUjL5cPTQn7ZWYomGoWlD2JqzPgf43Dt3PvxnOd0G+///nDdu2MXJj4tPm7laYGDZ03PwarA8celJpie72OfWx7/cF/cN1G+Npm1ed5EMpGolQMa1K0W381mLePeEwDaUwOxDb2NtLUD5tttJrKBNhS588UIFCMY9f8nlL5yBQD960pSw64VUkGQmwD/+EwiN8McTRnMpcRLyFGux9ahEP/8KfxGoMdJR572LHbYZwp964InFLTgXsalKsxlzy7GqTL16iGrpX9GDiKOuZjrK8dFQ4ymlDhe+AL36l09qyDzbwG1JgMb3AMLsUX09Ujw2NVH3+uiU5AHJqoVLC675eYZCbMOe/g/1+eCSJep4dX+4ph/MU95XnIsHYJqQOfqT+W1j6eF04znbYrC1RmwzAXfpYLcyGNiM04UHHI1LnRVowX/ZxAucKtEWwbni01/TnwOLlp5jWoe/Ql2KDmUoQEW9kAz8+KnsBZtv2H05KzXARxBLs/+qLp6djIAHZr+VOLpojXckuayKKnSt+SAOo0DLR1EF/4kbp1nhWIzYEez8645RjIii4S2K9JBce+Nn+AGjWhmPLusCiH/xedUApQEwwiL5mkDdHoceYTBRDhMKqcsfEmhOeaXae4cZXOOjaPRT9EmOqY1cfrunXca6X2kQtUmKYf78EIqeXuhbMiJRjkyWjBDDNp6WXtfKHzrSh94Q/iXKdDhN/RkLQxddiYNXpS+PQA5Q=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack-app-webhook
      namespace: monitoring
    type: Opaque

