apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: confluent-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgAU6OwfRwYzlG0+YrCVSAiIgIL9T+exX5QrDdCjUTQcgNIyML9+F5T37qe1VeFhotHfILoTk+xXNnN13sXBY0Y2/8mA0a4HGj9YQGyEEqYtKjjkwjr8g1AB5WLSfMHPFvFfE8h24AvvkcQpDNYbVc5ZAhEoWBn3HJaY9KV7oA2ZN+dZ24aTZ4e4W0nT635B+Uag0LNgyO07+Rp3MSKu39vTSpHsaLP0b1nYJ2kywWQOitM+k+AtPcryB9VGesOiyO/XGcn1NTQVDTXxu6uxFX2tcaDA1sE1oZ1VmliCgnnAq0iTDRg4M+WNOxWtaSCwnqxWmAv0kDP/CO1kUSA9K/g8t8pHlJNtXt8yLdA/rKG7lpG81lj55Ddhougu26jDJjYQ4uaoeN4eAffc46apyEUlt5GVVYtm3bsAWjlsXzJYPRiy2H6eNYtt/asW3qsdTgtKx1gDOWeUu5VTsJIoRprmpTmicWjOb+7frriUYvqDynm3FsLl0CKEHa/XYE1tPjBAQWRjfccqOmKeUTakMeQgHCoX3RC2oilmknIkF7JQZr9gteXzbCd1DmUpPEaZcQD2OF+SwaZ34z7TxzC2yQ0quhT1JEsFaaSJY45Ivm15bBdkOUnb2D3XPOmSdqb+/EzPa1uQYBX+ZzV0mSSPUmnpF9+/SLPm5Qy0R1Salf0zK2KeEj4dJfrx7bijPAYTiRSVu4vb/csBuYCsWkKzOqblwTkKbF3gN1OaG/ZArcIEH7G44qT6wOGEGdMX6emuLY/QEomNr+pDu+KscUnW/6rk
    username: AgDMqvLAMN+Oq+vVedIkRHUodeeTB3bksXEF7gq2m/d0YJfdakrrUgz7ebA9DPvrduWRKf1EzDorQHeASOw8mw2MkVRgv55Z/eTiNaXD8Oh4ACJsvVAaj/uKhnqOZ5ezn0sBNp64rRljBRMco9H8C+UF8ZFlK+x7QWurMAxPPRoLvws9RyS57/BPhWTyWv1Pneyxk0S2fs0E924RzqsXpmbUZgsx+E/7woqCNWPQJ5qKfbo06vJ0CH/CswxLAYqHTYjQ6jEaFU2CUx+lZo2Laxw0DU90mgU3/QQK5nQjKXwGBgJCtYtlvrFzPCOsix4kBw5AkQ6RSs/xTNJoTO+0Z9/h/rT3cb26uORM1fk8A/GdePE41KBq1yXo8TZ1eoInDm4t0hgL+djJvX3hoj3c4304vogT5nESFrBiHA2jW736yhPacKGuXSB4JYmXwF4lQiJczDl3ysEJGdfZz4U2nxLTdIcFu0YTECJ1lit4QZW9a/Cyth17sCgrizDqUa35NEjrZo/EZ7FdncBjCO7QZcwwvXyKdGBdb/OeJI923c/RBsSmK627Xiab12O9QWBl881XScFyR4vZqYNHo+6A34XD8mzySHoRpQZvHqWkTM+9OXotrK37edyQ/rX8th9qngspYxe/261UFr4WoQcvW0xZtQwiNqErCp+fggLAiIRnRHNZgrqS4Qth8+3Opw4lgfuYHxjLwhDnOC6ArlvQTp2A
  template:
    metadata:
      creationTimestamp: null
      name: confluent-credentials
      namespace: monitoring
    type: Opaque

